name: run-test-and-deploy
on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - main

jobs:
  run-test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: "x64"
      - run: pip install flake8
      - run: flake8 . --max-line-length 120 --statistics --count --exclude  ".venv,.env,.git,__pycache__,docs,old,build,dist"
      - run: pip install -r requirements.txt
      - run: coverage erase && coverage run ./manage.py test && coverage report

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        if: github.ref == 'refs/heads/main' && job.status == 'success'
        run: |
          git fetch --prune --unshallow
          git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git
          git push heroku HEAD:master -f
